# Trajectory Dimensions
TIME_FRAMES = 'time_frames'
TIME_DIM = 0
ATOMS = 'atoms'
ATOM_DIM = 1
FEATURE_DIM = 1
COORDINATES = 'coordinates'
COORDINATE_DIM = 2
COMBINED_DIM = 2
ALPHA_CARBONS = 'alpha_carbons'
