name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge, bioconda, defaults
          auto-activate-base: false
          activate-environment: dropp-algorithm
          environment-file: .conda.yml

      - name: Run unittests
        run: |
          python -m unittest discover -s test -p "test*.py"