name: Run Unit Tests

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file .conda.yml --name dropp-algorithm

      - name: Activate Conda and Run unit tests
        run: |
          $CONDA/bin/conda activate dropp-algorithm
          python -m unittest discover -s test -p "test*.py"