name: Run Unit Tests

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          environment-file: .conda.yml  # Specify the environment file

      - name: Run unit tests
        run: python -m unittest discover -s test -p "test*.py"